DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "harli",
    "number": "8989787878787"
}

###
PUT http://localhost:3001/api/persons/5fdaffd245aa4e6de65bb30c
content-type: application/json

{
    "name": "shiva",
    "number": "89897asdasd878787ff8asdasd7"
}